/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyApp;
import MyLib.Lot;
import MyLib.RealEstate;
import MyLib.User;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Jayvee
 */
public class BuyWindow extends javax.swing.JFrame {
    private RealEstate re;
    private User user;
    private Lot lot;
    private Dashboard dashboard;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BuyWindow.class.getName());
    
    /**
     * Creates new form RealEstateWindow
     */
    public BuyWindow(User user, Lot lot, Dashboard dashboard) {
        this.re = re;
        this.user = user;
        this.lot = lot;
        this.dashboard = dashboard;
        getContentPane().setBackground(java.awt.Color.BLACK);
        initComponents();
        
        DecimalFormat df = new DecimalFormat("#,##0.00");
        
        jLabel8.setText(String.valueOf(lot.getHouse().getBlockNumber()));
        jLabel9.setText(String.valueOf(lot.getLotNumber()));
        jTextField1.setText("Php " + df.format(lot.getTotalValue()));
        jTextField2.setText("Php " + df.format(lot.getDownpaymentFee()));
        jTextField4.setText("Php " + df.format(lot.getTotalValue() + lot.getDownpaymentFee()));
       
        jLabel6.setVisible(false);
        jScrollPane2.setVisible(false);
        jLabel5.setVisible(false);
        jComboBox2.setVisible(false);
        jTextField3.setVisible(false);
        
        this.pack();
    }
    
    private void calculateAndPopulateTable(String paymentMethod) {
        boolean isCash = paymentMethod.equals("Cash");
        
        jLabel6.setVisible(!isCash);
        jScrollPane2.setVisible(!isCash);
        jLabel5.setVisible(!isCash);
        jComboBox2.setVisible(!isCash);
        jTextField3.setVisible(!isCash);
        
        this.pack();

        if (isCash) {
            return;
        }

        double propertyPrice = lot.getTotalValue();
        double downPayment = lot.getDownpaymentFee();
        double loanAmount = propertyPrice - downPayment;

        DecimalFormat df = new DecimalFormat("#,##0.00");

        double annualRate = 0.09;
        int maxYears = 30;

        if (paymentMethod.equals("Bank")) {
            annualRate = 0.07; 
            maxYears = 20; 
        }

        double monthlyRate = annualRate / 12.0;
        int[] yearsArray = {30, 25, 20, 15, 10, 5};

        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable2.getModel();
        model.setRowCount(0); 

        jComboBox2.removeAllItems();

        for (int i = 0; i < yearsArray.length; i++) {
            int years = yearsArray[i];

            if (years > maxYears) {
                continue;
            }
            int totalMonths = years * 12;
            double monthlyPayment = 0;
            double gmiRequired = 0;

            if (loanAmount > 0) {
                double mathPower = Math.pow(1 + monthlyRate, totalMonths);
                monthlyPayment = loanAmount * (monthlyRate * mathPower) / (mathPower - 1);
                gmiRequired = monthlyPayment / 0.30;
            }

            model.addRow(new Object[]{years + " years", "Php " + df.format(monthlyPayment), "Php " + df.format(gmiRequired)});
            
            jComboBox2.addItem(years + " years");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField4 = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setBackground(java.awt.Color.black);
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Property Price:");

        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Downpayment fee:");

        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Total Price:");

        jTextField1.setEditable(false);
        jTextField1.setFocusable(false);
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jTextField2.setEditable(false);
        jTextField2.setFocusable(false);

        jTextField3.setEditable(false);
        jTextField3.setForeground(new java.awt.Color(255, 0, 0));
        jTextField3.setFocusable(false);
        jTextField3.addActionListener(this::jTextField3ActionPerformed);

        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("FINANCING & LOAN TERMS");

        jButton1.setBackground(new java.awt.Color(102, 204, 0));
        jButton1.setText("BUY PROPERTY");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("0");
        jLabel8.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("0");
        jLabel9.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("BLOCK ");
        jLabel10.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("LOT");
        jLabel11.setToolTipText("");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Bank", "Pag-Ibig" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Payment Method:");

        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Loan Term");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "30 years", "25 years", "20 years", "15 years", "10 years", "5 years " }));
        jComboBox2.addActionListener(this::jComboBox2ActionPerformed);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Loan Term", "Monthly Payment", "GMI Required"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTextField4.setEditable(false);
        jTextField4.setForeground(new java.awt.Color(255, 0, 0));
        jTextField4.setFocusable(false);
        jTextField4.addActionListener(this::jTextField4ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(56, 56, 56)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)))))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(jButton1))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String paymentMethod = jComboBox1.getSelectedItem().toString();
        boolean isCash = paymentMethod.equals("Cash");

        double userBalance = user.getCustomer()[User.getLoginIndx()].getBalance();
        double requiredPayment;
        
        //if Cash payment method
        if (isCash) {
            requiredPayment = lot.getTotalValue();
        } else {
            requiredPayment = lot.getDownpaymentFee();
        }        

        if (userBalance < requiredPayment) {
            JOptionPane.showMessageDialog(this, "Insufficient balance.");
            return; 
        }
        //If Pag-ibig or Bank payment method
        double loanAmount = 0;
        
        if (!isCash) {
            if (jComboBox2.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Please select a loan term.");
                return;
            }
            
            String selectedTerm = jComboBox2.getSelectedItem().toString();
            double userGMI = user.getCustomer()[User.getLoginIndx()].getGMI();
            double requiredGMI = 0;

            for (int i = 0; i < jTable2.getRowCount(); i++) {
                String tableTerm = jTable2.getValueAt(i, 0).toString();
                
                if (tableTerm.equals(selectedTerm)) {
                    String gmiString = jTable2.getValueAt(i, 2).toString().replaceAll("[^\\d.]", ""); //replaceAll removes Php from Monthly payment
                    requiredGMI = Double.parseDouble(gmiString);
                    break;
                }
            }

            if (userGMI < requiredGMI) {
                JOptionPane.showMessageDialog(this, "Gross Monthly Income too low for this term.");
                return; 
            }
            
            loanAmount = lot.getTotalValue() - lot.getDownpaymentFee();
        }

        System.out.println("[UPDATE]: Confirming Dialog");
        if (JOptionPane.showConfirmDialog(jButton1, "Would you like to buy the lot?", 
                "Notice", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            if (lot.getStatus() == "Reserved") {
                if (Lot.getUserLoginIndex() == User.getLoginIndx()) {
                    int result = dashboard.buyTheProperty(lot);
                    if (!lot.getStatus().equals("Sold")) {
                        try {
                            lot.setStatus("Sold");
                            System.out.println("[UPDATE]: Bought lot");

                            DecimalFormat df = new DecimalFormat("#,##0.00");
                            if (!isCash) {
                                double currentOwed = user.getCustomer()[User.getLoginIndx()].getTotalOwed(); 
                                user.getCustomer()[User.getLoginIndx()].addTotalOwed(currentOwed + loanAmount); 
                            }

                            JOptionPane.showMessageDialog(jButton1, "Bought the lot.");
                            dispose();
                        } catch(Exception e) {
                            System.out.println("[ERROR]: Unexpected behaviour occured.");
                        }
                    }
                }
            } else if (lot.getStatus().equals("Sold")) {
                System.out.println("[NOTICE]: Lot cannot be reserved or bought");
                JOptionPane.showMessageDialog(jButton1, "Lot is not available.");
            } else {
                int result = dashboard.buyTheProperty(lot);
                if (!lot.getStatus().equals("Sold")) {
                    try {
                        lot.setStatus("Sold");
                        System.out.println("[UPDATE]: Bought lot");
                            
                        DecimalFormat df = new DecimalFormat("#,##0.00");
                        if (!isCash) {
                            double currentOwed = user.getCustomer()[User.getLoginIndx()].getTotalOwed(); 
                            user.getCustomer()[User.getLoginIndx()].addTotalOwed(currentOwed + loanAmount); 
                        }
                        
                        JOptionPane.showMessageDialog(jButton1, "Bought the lot.");
                        dispose();
                    } catch(Exception e) {
                        System.out.println("[ERROR]: Unexpected behaviour occured.");
                    }
                }
            }
        } else {
            System.out.println("[UPDATE]: Did not reserve lot");
        }
        
        dashboard.updateBalanceLabel();
        dashboard.updateTotalOwed();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        calculateAndPopulateTable(jComboBox1.getSelectedItem().toString());       // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        if (jComboBox2.getSelectedItem() == null) {
                return;
        }
        
        String selectedTerm = jComboBox2.getSelectedItem().toString();
        
        for (int i = 0; i < jTable2.getRowCount(); i++) {
            String tableTerm = jTable2.getValueAt(i, 0).toString();

            if (tableTerm.equals(selectedTerm)) {
                jTextField3.setText(jTable2.getValueAt(i, 1).toString() + " /month");
                break;
            }
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
