/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyApp;
import MyApp.Startup;
import MyLib.Admin;
import MyLib.Agent;
import MyLib.RealEstate;
import MyLib.User;
import javax.swing.JOptionPane;

/**
 *
 * @author iancortez
 */
public class ManageAgent extends javax.swing.JFrame {
    private Admin admin;
    private RealEstate re;
    private User user;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageAgent.class.getName());

    /**
     * Creates new form manageAgent
     */
    public ManageAgent(Admin admin, User user, RealEstate re) {
        this.admin = admin;
        this.user = user;
        this.re = re;
        initComponents();
        loadAgentTable();
        getContentPane().setBackground(java.awt.Color.BLACK);
    }

    private void loadAgentTable() {
        javax.swing.table.DefaultTableModel model =
            new javax.swing.table.DefaultTableModel(
                new Object[][] {},
                new String[] {"Agent", "LicenseNo", "Status"}
            ) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    // Only allow editing in the Status column (index 2)
                    return column == 2;
                }
            };

        Agent[] agents = user.getAgent();
        int count = User.getAgentCnt();

        for (int i = 0; i < count; i++) {
            Agent a = agents[i];
            model.addRow(new Object[]{
                a.getUsername(),
                a.getLicenseNo(),
            });
        }

        jTable1.setModel(model);
        javax.swing.JComboBox<String> statusCombo =
            new javax.swing.JComboBox<>(new String[]{"Available", "Unavailable"});
        jTable1.getColumnModel().getColumn(2).setCellEditor(new javax.swing.DefaultCellEditor(statusCombo));
        for (int i = 0; i < count; i++) {
            model.setValueAt(user.getAgent()[i].getStatus().toString(), i, 2);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Agent", "licenseNo", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        saveButton.setBackground(new java.awt.Color(255, 0, 0));
        saveButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Save");
        saveButton.addActionListener(this::saveButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 81, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))))
            .addGroup(layout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(saveButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveButton)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Directory directoryWindow = new Directory(admin, user, re);
        directoryWindow.setLocationRelativeTo(null);
        directoryWindow.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        if (jTable1.getRowCount() == 0) {
            System.out.println("[CHECK]: No agents found.");
        } else {
            System.out.println("[CHECK]: Found agents.");
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                if (jTable1.getValueAt(i, 2) != null) {
                    switch(jTable1.getValueAt(i, 2).toString()) {
                        case "Available":
                            user.getAgent()[i].setStatus("Available");
                            System.out.println("[UPDATE]: Set agent " + (i + 1) + " status as Available");
                            break;
                        case "Unavailable":
                            user.getAgent()[i].setStatus("Unavailable");
                            System.out.println("[UPDATE]: Set agent " + (i + 1) + " status as Unavailable");
                            break;
                        default:
                            System.out.println("[ERROR]: Unexpected Behavior Occurred");
                            break;
                    }
                } else {
                    continue;
                }
            }
            JOptionPane.showMessageDialog(saveButton, "Successfully updated agents");
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
